### ISSUE TITLE
Possible issue in normalization

### ISSUE THREAD

**Issue by amini2nt** [kchua/handful-of-trials#11]
https://github.com/kchua/handful-of-trials/blob/e1a62f217508a384e49ecf7d16a3249e187bcff9/dmbrl/modeling/utils/TensorStandardScaler.py#L45

If the sigma is < 1e-12, you are setting sigma to 1 which does not do any scaling. Shouldn't it be

sigma[sigma < 1e-12] = 1e-12  ?

**Comment by kchua** [comment]
This was intentional, the intuition being that dimensions where sigma < 1e-12 over the dataset have negligible variation and essentially deterministic and should thus not be normalized.
