### ISSUE TITLE
More information on reacher task

### ISSUE THREAD

**Issue by KeAWang** [kchua/handful-of-trials#5]
I'm trying to understand the cost function for the reacher task which uses the function [here](https://github.com/kchua/handful-of-trials/blob/39d16fb469156f4fcc3f89e72fab0b0cf29a71f3/dmbrl/config/reacher.py#L100).
However, I can't find a reference for what each index of the observation is in the Reacher task in the OpenAI documentation. 

Can someone help explain what this function is computing? Also does anyone have a better source of documentation on the state observations in the Reacher task?

**Comment by kchua** [comment]
Each of the seven angles represents each of the joint angles, starting from the base of the robot to the end-effector (it follows the order of the joints in the corresponding xml file). All the function is doing is going through each of the angles to compute the position of the end-effector.

**Comment by KeAWang** [comment]
Is the 7-DOF reacher implemented in OpenAI gym? Where can I find out documentation about it?
