### ISSUE TITLE
Multi-GPU support?

### ISSUE THREAD

**Issue by h8907283** [kchua/handful-of-trials#6]
Hi Kurtland,

Thanks! This is great work! A quick question. Does this support multiple GPUs? I don't think I see settings that allow me to specify the number of GPUs used for training. If not, is there a plan to add it? If not, where should I look at for adding the support myself?

-C

**Comment by kchua** [comment]
Hi,

Thanks! Unfortunately, there aren't any plans in the near future for adding support for multiple GPUs. I'm not too familiar with how Tensorflow handles computations with multiple GPUs, but I'd imagine that the files in `dmbrl/modeling` would be a good place to start.
