### ISSUE TITLE
Could you explain the implementation of modeling variance?

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [kchua/handful-of-trials#7]
https://github.com/kchua/handful-of-trials/blob/master/dmbrl/modeling/models/BNN.py#L414-L415
Intuitively we can directly model the Gaussian variance using the output of last layer, but you created max_logvar&min_logvar. Could you explain this kind of implementation for variance?

**Comment by kchua** [comment]
max_logvar and min_logvar were included as part of the implementation to ensure prediction stability. In practice, we found that the variance predictions tended to be quite large away from data, rendering trajectory sampling methods unstable, so these two quantities were included to help alleviate the problem.

**Comment by TomorrowIsAnOtherDay** [comment]
Got it ! Thanks for your detailed explanation.
