### ISSUE TITLE
Running experiment on OpenAi Gym Mujoco Environment 

### ISSUE THREAD

**Issue by VuongLong** [kchua/handful-of-trials#8]
Dear author, 
In your in Environment, for example HalfCheetah, you access the reward function and use reward_run  and reward_ctrl separately instead of using original reward come from step(action) and you also add reward_run to first dim of state.

There are any config option that allow us evaluating on the original env provided by OpenAi Gym?

thank you so much for your support!

**Comment by kchua** [comment]
Evaluating on the original environment would be difficult since the agent would need to be able to evaluate the returns of action sequences that have not been applied to the environment (hence the addition of the reward_run to the state, so that it could be part of the prediction).

**Comment by archielee** [comment]
@kchua, sorry for reviving a dead thread but just wanted to clarify why the reward needs to be a part of the observation? Can I calculate the cost from the observed state using the same cost function as the MuJoCo environment like you do in the `cartpole` config module?
